name = "resume-processor-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[vars]
WORKER_TYPE = "resume-processor"
ENVIRONMENT = "development"

# Cloudflare AI binding
[ai]
binding = "AI"

# Environment-specific configurations
[env.staging]
name = "resume-processor-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
name = "resume-processor-production"
[env.production.vars]
ENVIRONMENT = "production" 
