/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ResumeDataContract {
  /**
   * Freeform version of this document format or record.
   */
  version?: string;
  /**
   * Target role/title.
   */
  desired_title: string;
  /**
   * Short professional summary.
   */
  summary: string;
  /**
   * Tag list of skills/technologies/competencies.
   */
  skills: string[];
  /**
   * Work history entries.
   */
  experience: {
    /**
     * Company or organization.
     */
    employer?: string;
    /**
     * Role/title held.
     */
    title: string;
    /**
     * Start date (YYYY-MM).
     */
    start: string;
    /**
     * End date (YYYY-MM), 'present', or null if ongoing.
     */
    end?: (string | "present" | "Present") | null;
    /**
     * Plain-text description of responsibilities/impact.
     */
    description: string;
    /**
     * Freeform location or timezone (e.g., 'Amsterdam, NL' or 'UTC+1').
     */
    location?: string;
  }[];
  location_preference?: {
    /**
     * Preferred working mode.
     */
    type?: "remote" | "hybrid" | "onsite";
    /**
     * Optional list of acceptable cities/countries/regions.
     */
    preferred_locations?: string[];
  };
  /**
   * Preferred engagement type.
   */
  schedule?: "full_time" | "part_time" | "contract" | "freelance" | "internship" | "temporary";
  salary_expectation?: {
    /**
     * ISO 4217 currency code (e.g., EUR, USD).
     */
    currency: string;
    /**
     * Lower bound of expected compensation.
     */
    min?: number;
    /**
     * Upper bound of expected compensation.
     */
    max?: number;
    /**
     * How the compensation is quoted.
     */
    periodicity: "year" | "month" | "day" | "hour" | "project";
    /**
     * Optional notes (e.g., equity/bonus expectations).
     */
    notes?: string;
  };
  /**
   * When the candidate can start (ISO 8601 date, or free text like '2 weeks notice').
   */
  availability?: string;
  /**
   * Optional portfolio/LinkedIn/GitHub links.
   */
  links?: {
    label: string;
    url: string;
  }[];
}
